hardware_interface:
  joints: ['front_left_wheel', 'rear_left_wheel', 'front_right_wheel', 'rear_right_wheel']
generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 1.0

diffbot_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  # (unless robot localization isn't running)
  enable_odom_tf: true

  # setting these will prevent the controller from parsing the urdf
  # but will it still complain about no urdf?
  # TODO(lucasw) probably should set these from the launch file,
  # and give them to the tracks.py script that generates the vehicle.
  wheel_separation: 1.0  # TBD
  wheel_radius: 0.2  # TBD
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.5 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2
